### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pursual** [jonkemp/gulp-bundle#1]
Its not terribly clear how this works. Is appdir the path to the *.html files or specifying the root for the search for the assets (usemin style). 

Is there a way to specify where the modified *.html files go or do they always go in the same folder as the assets?

**Comment by pursual** [comment]
Oh , I see you intent this to be used with your useref plugin. 

Its too bad useref can take in a gulp.src blob but this one just goes through a whole folder and is limited to *.html.   That being said I guess you could get a basic usemin functionality by combining the two.

**Comment by jonkemp** [comment]
Yes, that's correct. I will update the documentation to be more clear on that. Thanks!

**Comment by pursual** [comment]
Instead of having it glob a folder, can you have it accept a filename as an
option? That way it could be used for *.jade and also with gulp.src (just
without piping)

Personally I think you should just make it a plugin but I get your
reservations.

**Comment by jonkemp** [comment]
Yes, I will probably release an update to have it accept the path to glob as an option. I had the same thought.

**Comment by jonkemp** [comment]
991d358858372ba45aa85983df1ddb2f9475a118 adds the ability to pass in the path to your files.
