### ISSUE TITLE
Inplace or destination path

### ISSUE THREAD

**Issue by koen-serry** [jonkemp/gulp-bundle#2]
I'm trying this plugin, but I'm wondering how to approach the issue where when you've got a certain number of html files containing the bundle feature and a certain other number not. I see two approaches: 
- eiher do the 'bundle' inline and replace the files after reading
- use a target, but just copy over the ones without the need of bundling them.

Please advise

**Comment by jonkemp** [comment]
Can you post a code example of what you are wanting to do so that I can get some more details?

**Comment by koen-serry** [comment]
Well say I've got 3 html files and 1 of them contains a ""

in which case I want all 3 html either in the destDir or bundle the admin.js inplace (ie. in the same folder)

**Comment by jonkemp** [comment]
Wouldn't you just use it with gulp-useref like this?

``` js
var gulp = require('gulp'),
    useref = require('gulp-useref'),
    bundle = require('gulp-bundle');

gulp.task('bundle', bundle('./app/*.html', {
    appDir: 'app',
    buildDir: 'build',
    minify: true
}));

gulp.task('html', function(){
    return gulp.src('./app/*.html')
        .pipe(useref())
        .pipe(gulp.dest('build/'));
});

gulp.task('build', ['bundle', 'html']);
```
